### PR TITLE
Fix broken dependency

### PR DESCRIPTION
**Pull request by MattTheCuber**

### CODE REVIEW

**Comment by MattTheCuber** [comment]
@ZhiyLiu or @FabianIsensee can this be merged?

**Comment by FabianIsensee** [comment]
Please take a look at the current master. The dependency is already fixed

**Comment by MattTheCuber** [comment]
> Please take a look at the current master. The dependency is already fixed

That's because this PR got merged into master?

**Comment by FabianIsensee** [comment]
this was merged into @ZhiyLiu 's master, not the nnunet master

**Comment by MattTheCuber** [comment]
> this was merged into @ZhiyLiu 's master, not the nnunet master

Oh! My bad xD

**Pull request merged**
